### ISSUE TITLE
encryptor has not main source file

### ISSUE THREAD

**Issue by yanghaoi** [0xsp-SRD/mortar#1]
Hi, 
Mortar is a awesome project! But, I have some trouble that i get a error with "encryptor has not main source file" when i use kail to build the encryptor project.  I don't know why.  Can you provide a encryptor file  and  a calc.enc file ? Thank you please ~

**Comment by lawrenceamer** [comment]
thanks, can you please provide more logs to dig into the problem, I am glad to fix the problem, I will keep this issue ticket open in the case released the encryptor as Linux version

**Comment by yanghaoi** [comment]
Yes.And this is the first time that I used this program(Lazarus). I installed it in kali , then i choice encryptor  project and build it,i get this:
![](https://user-images.githubusercontent.com/21354684/146676074-6649d0af-3609-4838-99a1-6701d77f9b02.png)

I was install  Lazarus in windows too. I copied encryptor.lpr code to deliver.lpr and build successful........
![](https://user-images.githubusercontent.com/21354684/146676382-8a5c2222-d3b0-4a14-8834-2d6916f56a7d.png)

But when I run `deliver.exe -d -f bin.enc` I get a EReadError:
```
Exception at 0000000100010930: EReadError:
Stream read error.
```

**Comment by lawrenceamer** [comment]
thanks for your testing, there was a bug in the encryptor and encryption key, I have pushed the fix please clone the new repo and have a test, make sure to be root to avoid permission locking, I have added also an encrypted version of mimikatz for testing. let me know your testing results again. 
https://github.com/0xsp-SRD/mortar/commit/18736a408b53ad0ff3d62c97a4d08b976e14518d

**Comment by yanghaoi** [comment]
Nice! The encryptor It's working(win and kali). And thank you for your enthusiastic help. I greatly appreciate it.

![](https://user-images.githubusercontent.com/21354684/146686190-8c71e7a5-5cc0-49d9-905a-e28cca44924c.png)
