### ISSUE TITLE
DLL Error and Defender Detecting Payload

### ISSUE THREAD

**Issue by jm0202** [0xsp-SRD/mortar#10]
deliver.exe is detected by AV and deleted. Whenever I try to run agressor.dll I get this:
![image](https://user-images.githubusercontent.com/68917195/150387700-f1e1c4c7-d23f-4602-b71b-b0ede556e05f.png)

**Comment by lawrenceamer** [comment]
that because you have compiled your DLL in Debug mode, change it to release mode and try again.there is new version comes after a time to bypass again

**Comment by jm0202** [comment]
No i am not. The whole project is set up to release
![image](https://user-images.githubusercontent.com/68917195/150537707-b290df2e-f764-401f-a6b4-6886ac276a95.png)
