### ISSUE TITLE
Detected by windows defender

### ISSUE THREAD

**Issue by TH3P1T** [0xsp-SRD/mortar#12]
Both agressor and deliver are detected by windows defender.

**Comment by lawrenceamer** [comment]
thanks for the testing, yeah I have noticed that it has been detected but since WD uses static analysis for detection, any possible modification to the main unit could do the bypass, I have already bypassed it now, not going to publish it soon 
![image](https://i.ibb.co/mBBNqWV/bypass2.png)

**Comment by lawrenceamer** [comment]
solved
