### ISSUE TITLE
Inject dll into cmd.exe process and call "dec" function to execute my ".enc" payload.

### ISSUE THREAD

**Issue by Jack-Reve** [0xsp-SRD/mortar#14]
Hello lawrenceamer, hope you are well.
I have a question, how can I call the export function "dec" and execute it when I injected the dll into "cmd.exe" process, or what is the technique, the reflective injector you are used to do that.
because when I injected the dll into the cmd.exe process it is just injected and didn't execute "dec" function to run the ".enc" payload.

**Comment by lawrenceamer** [comment]
I didn't understand your question, but if you wanna call the specific DLL export function 
`rundll32 mortar.dll,dec`
