### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by evildrummer** [0xsp-SRD/mortar#16]
The IDE claims that "runner" was not found. The folder "..\Lib" is imported and the files are there.

![image](https://user-images.githubusercontent.com/16805842/169782986-97b29045-53da-42f4-8b50-56ca720ca2c4.png)

**Comment by lawrenceamer** [comment]
i am not sure why is that happening to you, try to restart your IDE or make sure you install it correctly, i have done several tests and works fine

**Comment by fracool** [comment]
I'm also having this problem @evildrummer , what solved it for you?

**Comment by evildrummer** [comment]
I'll install a new win 10 and start agein with a clean system. Can report my progress in two days or so.

**Comment by fracool** [comment]
Thanks, I’ll be interested in how you get on!

**Comment by fracool** [comment]
@evildrummer cheers for the follow up, that’s the info I needed! :) Bummer about the detection but maybe a slight modification will be enough…
