### ISSUE TITLE
Error: identifier idents no member "rdx"

### ISSUE THREAD

**Issue by nathan-bowman** [0xsp-SRD/mortar#17]
![image](https://user-images.githubusercontent.com/2992876/169898965-b9778af8-e0fb-4941-8d6b-2737f85d1e68.png)

I'm pretty new to Lazarus/Pascal. What's going on here?

**Comment by lawrenceamer** [comment]
you need x64 of Lazarus_IDE, right now i am only supporting x64 for v2, to reduce detection ratio
