### ISSUE TITLE
Agressor.dll doesn't work

### ISSUE THREAD

**Issue by jad017** [0xsp-SRD/mortar#19]
I'm having the same issue as nathan-bowman. The encryptor works. I compile the DLL, but I can't run it. I have compiled it on 3 different systems (all windows x64-one windows 10, two windows 11, one bare-metal two VM's). I've tried to run it with the mimikats.enc. (rundll32.exe agressor.dll,start), also on multiple machines. Nothing happens.

**Comment by lawrenceamer** [comment]
there is something wrong with your testing, I can't figure out, I have tested and many tested mortar with windows 10, 11 and works fine, I am not sure why that happen, any way send plz the following and I will test accordingly 
```
OS : 
CPU: 
RAM:
```

**Comment by lawrenceamer** [comment]
![image](https://user-images.githubusercontent.com/10256911/170633543-14c6ed00-dc64-4776-ac99-1f699dad32e2.png)

**Comment by lawrenceamer** [comment]
try also to use the following demo to make sure if your DLL compiled correctly https://github.com/0xsp-SRD/mortar/blob/main/demo/bin.enc

**Comment by lawrenceamer** [comment]
duplicate #18
