### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by fre3vil** [0xsp-SRD/mortar#22]
While compiling agressor with the release version, it shows three lines error.

syscalls.RPM(PI.hProcess, Pointer(CONT.rdx + $100), @Addr, 4, Ret);        
// runner.pas(134,52) Error: identifier idents no member "rdx"

syscalls.W_M(PI.hProcess, LPVOID(CONT.rdx + $10), @ImageBase, 8, Ret);  
// runner.pas(179,53) Error: identifier idents no member "rdx"

CONT_B.rcx := dword64(ImageBase) + INH.OptionalHeader.AddressOfEntryPoint;  
// runner.pas(190,22) Error: identifier idents no member "rcx"

**Comment by lawrenceamer** [comment]
USE X64 IDE ONLY
