### ISSUE TITLE
I want to pass command  

### ISSUE THREAD

**Issue by ifconfig2333** [0xsp-SRD/mortar#23]
you able to pass commands for the loaded binary

you deleted the exe, how do i pass the command

I need the program to receive commands

**Comment by lawrenceamer** [comment]
may insert your command like this https://github.com/0xsp-SRD/mortar/blob/main/DLL/agressor.lpr#L191
```
bin_decryptor('c:\\windows\\system32\\cmd.exe /c sekulra::logonpasswords' );
```
could work with DLL

**Comment by ifconfig2333** [comment]
Thank you for your answer. This is a success.

still have a question. Can the exe inside be replaced?

or calc.exe

`bin_decryptor('c:\\windows\\system32\\calc.exe');`

**Comment by lawrenceamer** [comment]
it should be CLI application that accepts command args only

**Comment by ifconfig2333** [comment]
Hello lawrenceamer, today I found that windows defender can check this DLL can you modify it. thank you

**Comment by mooneee** [comment]
> 

removed by defander

**Comment by mooneee** [comment]
dll removed by defander
