### ISSUE TITLE
Stealthier injection

### ISSUE THREAD

**Issue by stevenhay** [0xsp-SRD/mortar#25]
Hi,

Firstly, absolutely love the work!  Very much appreciate it.

Is there anyway to make the injection process stealthier? At the moment, a cmd window is launched and simply stays there, closing it also ends the meterpreter session. I've attempted to recompile the loader and inject into different processes such as 'svchost.exe' and 'explorer.exe' via

`bin_decryptor('c:\\windows\\explorer.exe'); ` or `fork_P_x64('C:\\windows\\explorer.exe',runner.TByteArray(AMemStr2.memory),processhandle);` 

yet only the CMD window opens and nothing else, and again closing the CMD window ends the session.

also, I know literally nothing about the pascal language

**Comment by lawrenceamer** [comment]
Hi @stevenhay 
Thanks!, that's true there is no stealthier injection, as the execution will end when it is terminated, but have you tried to inject the DLL into an existing process? Maybe watch this https://video.0xsp.com/conversations/eb396ad5-f9f1-5afa-b171-30b812c8a9de. 

However, i am planning to release some updates in 2023, hopefully, i can find much time for the mortar loader

**Comment by stevenhay** [comment]
I did try but unless I'm doing something wrong the CMD window kept appearing. I tried a couple of processes, "explorer.exe" and "svchost.exe". I did this by changing the calls to `bin_decryptor('...')` and tried hardcoding it in the `fork_P_x64` process as well, but both seemed to have no effect. 

Is this the wrong place to be changing which process it's injected into?

**Comment by lawrenceamer** [comment]
better to share error output or some screenshots @stevenhay
