### ISSUE TITLE
Microsoft defender started detecting 

### ISSUE THREAD

**Issue by hackzzdogs1337** [0xsp-SRD/mortar#7]
From today Microsoft defender started detecting it as Virus tool with label VirTool/Win64Mortar :\

**Comment by GroteHersenen** [comment]
It got added in the Security intelligence update version: 1.355.1751.0.
[https://www.microsoft.com/en-us/wdsi/definitions/antimalware-definition-release-notes?requestVersion=1.355.1751.0](url)

**Comment by lawrenceamer** [comment]
did you try to upx it? compile the DLL then upx it and let me know the results

**Comment by hackzzdogs1337** [comment]
Yeah tried it its still getting flagged.

**Comment by lawrenceamer** [comment]
successfully bypassed, will push the update later 
![image](https://i.ibb.co/rb02hf5/bypass-def.png)

**Comment by jm0202** [comment]
deliver.exe is detected by AV and deleted. Whenever I try to run agressor.dll I get this:

![image](https://user-images.githubusercontent.com/68917195/150355350-ed2c1c9b-ce5f-46f3-863a-098155658824.png)
